# Generated by Django 5.0.1 on 2024-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(default='default_audio/default.mp3', upload_to='audio_files/'),
        ),
    ]
