# Generated by Django 5.0.1 on 2024-02-09 14:43

import app.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_file_name_audio_name_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(default='default_audio/default.mp3', upload_to='audio', validators=[app.validators.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='audio',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
